name: coverage
on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Report Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20.5"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          go mod download

      - name: Run tests with coverage output
        run: |
          go test -race -covermode atomic -coverprofile=coverage.out ./...
          go tool cover -func coverage.out | grep total

      - name: Send coverage
        run: |
          value100=$(go tool cover -func coverage.out | grep total | awk '{print $3}')
          echo "Coverage is ${value100}"
          curl -XPUT "https://rcc.evertras.com/api/v0/coverage?key=github.com/Evertras/rcc&value100=${value100}"

